### start
POST localhost:8080/api/start
Content-Type: application/json

{
  "strategyKey": "simple"
}


### stop
POST localhost:8080/api/stop
Content-Type: application/json

{
  "strategyKey": "simple"
}

### test
GET localhost:8080/test
