name: dev ci/cd
# To automatically trigger a workflow, use "on" to define which events can cause the workflow to run
on:
  workflow_dispatch:
    inputs:
      profile:
        required: true
        type: string
        description: 'profile name of spring boot application'
      branch:
        required: true
        type: string
        description: 'branch to deploy'
# A workflow run is made up of one or more "jobs", which run in parallel by default.
jobs:
  # "build" is job_id it is unique identifier
  build:
    # define the type of machine(runner) to run the job on.
    runs-on: ubuntu-latest
    # A job contains a sequence of tasks called "steps". Steps can run commands,
    steps:
      # step 1 : check-out
      - name: check-out
        # "uses" keyword is used within a "step" and specify it should use "actions"
        uses: actions/checkout@v4 # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
        with:
          ref: ${{ github.event.inputs.branch }}
      # step 2 : Set up JDK 17
      - name: set up jdk temurin 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      # step 3: build with gradle
      - name: build with gradle
        run: | # pipe character in is used to define multiline string
          chmod +x ./gradlew
          ./gradlew clean build -x test
      # step 4,5,6 : build and push the docker image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image based on profile
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # This dynamically selects the tag based on the input profile
          tags: ${{ secrets[format('{0}_DOCKER_IMAGE', github.event.inputs.profile)] }}
      # step 8~10 : deploy
      - name: Create env file to transfer to ec2
        run: |
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env
          echo "DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_TOKEN }}" >> .env
          echo "DOCKER_IMAGE=$${{ secrets[format('{0}_DOCKER_IMAGE', github.event.inputs.profile)] }}" >> .env
          echo "BINANCE_APIKEY=$${{ secrets[format('{0}_BINANCE_APIKEY', github.event.inputs.profile)] }}" >> .env
          echo "BINANCE_APISECRET=$${{ secrets[format('{0}_BINANCE_APISECRET', github.event.inputs.profile)] }}" >> .env
          echo "MONGODB_URI=$${{ secrets[format('{0}_MONGODB_URI', github.event.inputs.profile)] }}" >> .env
      - name : Copy env file to ec2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets[format('{0}_SSH_HOST', github.event.inputs.profile)] }}
          username: ${{ secrets[format('{0}_SSH_USER', github.event.inputs.profile)] }}
          key: ${{ secrets[format('{0}_SSH_PEM_KEY', github.event.inputs.profile)] }}
          source: .env
          target: ~/
      - name: connect to ec2 and deploy
        env:
          SSH_HOST: ${{ secrets[format('{0}_SSH_HOST', github.event.inputs.profile)] }}
          SSH_USER: ${{ secrets[format('{0}_SSH_USER', github.event.inputs.profile)] }}
          SSH_PEM_KEY: ${{ secrets[format('{0}_SSH_PEM_KEY', github.event.inputs.profile)] }}
        run: |
          echo "$SSH_PEM_KEY" >> $HOME/key.pem
          chmod 400 $HOME/key.pem
          ssh -i $HOME/key.pem -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            set -e
            source ~/.env
            sudo dnf install docker -y
            sudo systemctl start docker
            echo $DOCKERHUB_PASSWORD | sudo docker login --username $DOCKERHUB_USERNAME --password-stdin
            sudo docker-compose down
            sudo docker-compose pull
            sudo docker-compose up -d
            sudo docker image prune -a -f
            rm ~/.env
          EOF
